# Generated by Django 3.0.8 on 2020-07-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(verbose_name='Organizer'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Concert', 'Concert'), ('Corporate', 'Corporate'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('DJ', 'DJ'), ('Workshop', 'Workshop'), ('Drama', 'Drama'), ('Others', 'Others')], max_length=14)),
                ('description', models.CharField(max_length=200)),
                ('seats', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
