# Generated by Django 3.0.8 on 2020-07-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200723_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='time',
        ),
    ]
