# Generated by Django 3.0.8 on 2020-07-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_movie_is_showing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='screens',
        ),
    ]
